### PR TITLE
feat: set queue properties

### LINKED ISSUE #92: feat: ensure logging is enabled for queue service for read, write and delete requests (CKV_AZURE_33)
Guide: https://docs.bridgecrew.io/docs/enable-requests-on-storage-logging-for-queue-service

### PR DESCRIPTION
**Pull request by sebastianlolv**
Closes #92

### CODE REVIEW

**Comment by sebastianlolv** [comment]
Go tests passed on my machine + passed on the checkov check.

**Comment by hknutsen** [comment]
Might need to implement something similar to #100 to prevent trying to set queue properties when queue storage is disabled.

We should also implement a few new tests (or cases for an existing test) to test the different storage kinds (storagev2, blobstorage, filestorage ...).

**Comment by hknutsen** [comment]
#103 should be merged before this, as it might change the implementation in this PR.

**Comment by sebastianlolv** [comment]
Can we merge this now?

**Review by helenakallekleiv — COMMENTED** [review]
Terraform [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#queue_properties) states that `queue_properties` cannot be set when the `account_kind` is set to `BlobStorage`. Wouldn't this, being hard-coded, affect the test examples with `account_kind = BlobStorage` if merged? I'll run a test to confirm.

**Comment by hknutsen** [comment]
> Terraform [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#queue_properties) states that `queue_properties` cannot be set when the `account_kind` is set to `BlobStorage`. Wouldn't this, being hard-coded, affect the test examples with `account_kind = BlobStorage` if merged? I'll run a test to confirm.

Working on it 😄

**Comment by hknutsen** [comment]
Tests pass 🎉

**Comment by hknutsen** [comment]
@sebastianlolv Merge away 🏄

**Pull request merged**
