### PR TITLE
feat!: enforce blob properties

### LINKED ISSUE #162: feat!: enforce blob properties
Blob properties should be enforced (i.e. remove `blob_properties` variable), however you should still be able to customize each property (i.e. create granular variables for each property).

### PR DESCRIPTION
**Pull request by hknutsen**
Fixes #162

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass :tada:

**Review by sebastianlolv — DISMISSED** [review]
Tests pass 🎉

**Comment by hknutsen** [comment]
Need new review after resolving merge conflict.

**Review by helenakallekleiv — APPROVED** [review]
👍🏼

**Review by sebastianlolv — APPROVED** [review]

**Pull request merged**
