### PR TITLE
refactor: add checks for HNS and service properties

### PR DESCRIPTION
**Pull request by ErlendT**
Added some checks that decreases the input needed when creating a storage account with hns and checks for different kinds of storage.

### CODE REVIEW

**Comment by hknutsen** [comment]
Modifications made to module code, however no changes in functionality, so marking this as `refactor`.

**Comment by hknutsen** [comment]
Ultimately this is a very good suggestion, however I wouldn't want to merge it until we've come to a decision collectively.

**Comment by ErlendT** [comment]
@hknutsen I see your point. A solution could be creating a datalake module, but that could quickly miss out on benificiary updates from this repo. I agree that we should not add complexity for complexitys sake, but I think in cases where it provides a reasonable benefit to the end user it should maybe be allowed.

For an example a user withould prior knowledge of this module could potentially hit 5 errors in succession on when trying to create a premium block blob storage with hns enabled.
This is not a huge issue, but I think the modules should be designed in a way that they can be used without to much prior indepth knowledge of the module itself.

**Comment by hknutsen** [comment]
@ErlendT I agree that this PR is much better than creating a separate datalake module 🙂

**Comment by stiross79** [comment]
I also thinks that this addition will reduce the number of errors when you create a storage account with hierarchical namespace enabled.

**Comment by hknutsen** [comment]
I'll update tests (#145) to verify the values of blob, share and queue properties, then I'll look into getting this merged 😊

**Comment by hknutsen** [comment]
Tests pass 🎉

**Review by hknutsen — APPROVED** [review]

**Comment by hknutsen** [comment]
@equinor/ops-coredev Could one of you have a look before we merge this?

**Review by helenakallekleiv — APPROVED** [review]
@hknutsen All tests pass for me 👍🏼

**Pull request merged**
