### PR TITLE
chore: create storage for critical data are encrypted with customer managed key example (CKV2_AZURE_1)

### LINKED ISSUE #94: chore: create storage for critical data are encrypted with customer managed key example (CKV2_AZURE_1)
Guide: https://docs.bridgecrew.io/docs/ensure-storage-for-critical-data-are-encrypted-with-customer-managed-key

### PR DESCRIPTION
**Pull request by sebastianlolv**
Closes #94

### CODE REVIEW

**Comment by sebastianlolv** [comment]
image
Cant seem to get it to work when deploying through Go Test.

**Comment by sebastianlolv** [comment]
Test passes locally.👍

**Review by helenakallekleiv — APPROVED** [review]
Test passed 🎉

**Comment by hknutsen** [comment]
@sebastianlolv adding new outputs should've been its own feature PR 👀 

I'd also rename the identity related outputs to follow same convention as other modules, e.g. https://github.com/equinor/terraform-azurerm-web-app/blob/v10.2.2/outputs.tf#L21-L24

**Pull request merged**
