### PR TITLE
fix: validate network IP rules

### PR DESCRIPTION
**Pull request by hknutsen**
Validate network IP rules to prevent passing invalid values to Storage account resource.

### CODE REVIEW

**Comment by hknutsen** [comment]
@equinor/terraform-baseline An idea I had.

Storage account network IP rules do not support prefixes >30, so if you want a `/32` prefix you should just omit the prefix, and if you want a `/31` prefix you should just specify both addresses in the range without a prefix instead.

My implementation automatically removes the prefix for any IP addresses >30, which simplifies the config of `/32` ranges, however it does not automatically add both addresses for a `/31` range.

So, two questions:

1. Do you agree that doing this automatically would simplify Storage account configuration using this module? Or do you see potential issues if we implement this?
2. Do you have any better idea of how to configure `/31` address ranges properly?

**Comment by hknutsen** [comment]
Updated logic to add hosts to list for both `/31` and `/32` prefixes 🙂

**Review by helenakallekleiv — DISMISSED** [review]
I like 👍🏼

**Comment by hknutsen** [comment]
Alternatively, document in variable description that only 0-30 bits are supported.

**Comment by hknutsen** [comment]
Updated to simply specify limitation.

**Review by sefornes — DISMISSED** [review]
LGTM 👍🏻

**Comment by helenakallekleiv** [comment]
> Updated to simply specify limitation.

What prompted the change to simply specifying the limitation versus the logic implementation?

**Comment by hknutsen** [comment]
@helenakallekleiv 

1. Wasn't able to implement required logic without relying too much on the `try` function, which is considered a bad practice as it simply suppresses errors.
2. Modifying user input could confuse users, as the module may behave differently than what is expected based on the input (even though the expected behavior is an error).

**Comment by stiross79** [comment]
Maybe use variable validation here ?

I.E

```powershell
variable "network_rules_ip_rules" {
  description = "The public IPs or IP ranges in CIDR format that should be able to access this Storage account. Only IPv4 addresses with 0-30 number of bits as prefix are allowed."
  type        = list(string)
  default     = []
  validation {
    condition = (
      strcontains(join(",", var.network_rules_ip_rules), "/31") ||
      strcontains(join(",", var.network_rules_ip_rules), "/32")
    )
    error_message = "Only IPv4 addresses with 0-30 number of bits as prefix are allowed."
  }
}
```

**Comment by BouvetMorten** [comment]
Tested module using source: git::github.com/equinor/terraform-azurerm-storage.git?ref=1af039d1e9360b4e75819f540ef99fbc7eef7a98.

When entering valid ip range 80.22.76.43/30 plan ran fine.
When entering invalid ip range 80.22.76.43/31 or 80.22.76.43/32 it provided error as expected:
image

Looks good!

**Review by BouvetMorten — APPROVED** [review]

**Pull request merged**
